# Lesson 9: NumPy Arrays I

**WARNING:** The reference notebook is meant **ONLY** for a teacher. Please **DON'T** share it with any student.

The contents of the reference notebook are meant only to prepare a teacher for a class. To conduct the class, use the class copy of the reference notebook. The link and the instructions for the same are provided in the **Notes To The Teacher** section.


|Particulars|Description|
|-|-|
|**Topic**|NumPy Arrays I|
|||
|**Class Description**|In this class, a student will learn how to create a NumPy array|
|||
|**Class**|C9|
|||
|**Class Time**|45 minutes|
|||
|**Goals**|Create a NumPy array using various functions|
||Convert a NumPy array into a Python list using the `list()` function|
|||
|**Teacher Resources**|Google Account|
||Link to Lesson 9 Colab reference notebook|
||Laptop with internet connectivity|
||Earphones with mic|
|||
|**Student Resources**|Google Account|
||Laptop with internet connectivity|
||Earphones with mic|

---

### Class Structure

A class is divided into three parts, as shown in the table below.

|Parts|Duration|
|-|-|
|**Warm-Up**|5 minutes|
|||
|**Teacher-Student Activities**|35 minutes|
|||
|**Wrap-Up**|5 minutes|

---

### Notes To The Teacher

Before beginning the class:

1. Open the **AT - Lesson 9 - Class Copy - v0** file by clicking on the link provided in the **Activities** section under the title **NumPy Arrays I (Class Copy)**.  

2. After opening the file mentioned in the first point, create its duplicate copy by following the steps described below:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

    - In the duplicate copy, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/2_share_button.png' width=500>

    - Click on the tiny downward arrow next to **Anyone with the link can view** text. A drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/3_anyone_can_view.png' width=500>

    - Click on the **More...** option. A new page on the dialog box will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/4_more_option.png' width=500>

    - Click on the circle next to **On - Anyone with the link** option. Now, go down and click on the tiny downward box next to **Can edit** text. A drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/5_anyone_with_the_link.png' width=500>

    - Click on the **Can edit** option. Then click on the **Save** button. You will be directed back to the first page of the dialog box.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/6_can_edit.png' width=500>

    - Make sure that under the **Link sharing on** section, **Anyone with the link can edit** option is selected.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/7_anyone_can_edit.png' width=500>

    - Then click on the **Done** button.

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Lesson9** format.

4. Now, finish the **Warm-Up** section. Afterwards, proceed with the class using the duplicate copy of the notebook. You can share the link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Lesson9**) with the student through the chat window.

5. When a student executes the code for the first time in the duplicate copy that you shared with them, they may get the following warning:

   ```
    Warning: This notebook was not authored by Google. This notebook was
    authored by xyz@gmail.com. It may request access to your data stored
    with Google such as files, emails and contacts. Please review the source
    code and contact the creator of this notebook at xyz@gmail.com with any
    additional questions.

                                                      Cancel. Run Anyway.
  ```

6. Ask the student to click on the `Run Anyway` button.

7. Wherever you see the hat (**^**) sign on the heading of activity, give a hats-off to the student at the end of the activity.

    - Single hat sign, i.e., **^** denotes give hats-off for concentration. You have to assess the concentration level of a student based on their attentiveness and understanding of the concept.

    - Double hat signs, i.e., **^^** denotes give hats-off for creativity. It can be an alternative approach to writing a code for an activity or applying the logic in a totally different problem statement.

    - Triple hat signs, i.e., **^^^** denotes give hats-off for persistence. It is the ability of a student to not give up on writing code and writing code with minimal teacher support.

8. Every time you execute your code in the Google Colab notebook, please don't forget to save it by pressing the **Ctrl + S** keys (or **Command + S** keys if you are using a Mac). While saving the notebook, you or student may encounter the following error:

   ```
    Save failed
    
    The notebook has been changed outside of this session. Would you like to
    overwrite existing changes?
    
                                                              CANCEL    YES
   ```

   Click on the `YES` button.

9. Occasionally, you may encounter some error such as `NameError, ReferenceError, ImportError` or `ModuleNotFoundError` after executing the code in $k^{th}$ code cell (where $k > 0$). Most likely, due to poor internet speed, the Colab notebook might have lost the information that all the previous codes have been executed already. As a remedy, run codes in the code cells beginning from the first code cell till the $(k - 1)^{th}$ code cell. For e.g., if the code in the $5^{th}$ code cell fails to run because of one of the aforementioned errors, execute the codes in all the first four code cells again.

10. For every **Teacher Action**, the teacher is supposed to share their screen with the student. Similarly, for every **Student Action**, the student is supposed to share their screen with the teacher.

---

### Warm-Up

```
TEACHER
  Hi student_name! How are you doing?

EXPECTED STUDENT RESPONSE
  I am doing good, teacher. How about you?


TEACHER
  I am having a good time, thank you. So, how was your day? What did you do
  today?

EXPECTED STUDENT RESPONSE
  I went to school. Had my lunch. Played a game and then did my homework
  before this class.


TEACHER
  That's great. I am glad that you are having a good day. Now, let's do a
  quick recap of our previous class. Can you recall the concepts you
  learnt in the previous lesson?

EXPECTED STUDENT RESPONSE
  We learnt how to create a Python list using the list comprehension method.


TEACHER
  Excellent! You recalled everything that you learnt in the last class.
  Great job! Keep it up.
  I have an exciting quiz question for you! Are you ready to answer this question?    
  ```   
  **Instructions for the Teacher:**
  -  Please click on the "Quiz Time" button on the bottom right corner of your screen to start the In-Class Quiz.<img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/quiz-time.png' width=100>   
  - A quiz will be visible to both you and the student. Encourage the student to answer the quiz question.
  - The student may choose the wrong option, help the student to think correctly about the question and then answer again.
  - After the student selects the correct option, the "End Quiz" button will start appearing on your screen.  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/end-quiz.png' width=100>  
  - Click the "End quiz" to close the quiz pop-up and continue the class.
  - Do not spend more than 2 minutes on this quiz.

```
TEACHER
  Today, we are going to learn NumPy arrays. They are
  more efficient and powerful compared to Python lists.
  NumPy arrays are widely used for major mathematical computations.
  
  So, are you excited for this class?

EXPECTED STUDENT RESPONSE
  Yes, teacher.


TEACHER
  All right. Let's get started. I'm sharing the link of the Colab notebook
  for this class.

  Note:
    - Share the duplicate copy of the notebook that you just created with
      the student through the chat window.
    
EXPECTED STUDENT RESPONSE
  The student opens the Colab notebook.
```

---

### Teacher-Student Activities

In the previous lesson, we learnt how to create a Python list using the list comprehension method. In this lesson, we are going to learn how to create NumPy arrays.

An array is also a data-structure which contains multiple values. Working with NumPy arrays is much easier than working with Python lists.

The term NumPy stands for Numeric (or Numerical) Python. It is one of the most popular modules amongst Statisticians and Data Scientists across the globe to perform heavy mathematical computations. NumPy arrays are also faster than Python lists in terms of code execution time.

For all practical purposes, **an array is the same as a list**. Fundamentally, they have been programmed differently by the inventors of Python language. We are **NOT** required to know how they were created. We only need to know how to apply them in different situations.

---

#### Activity 1: NumPy Arrays - The `ones()` & `zeros()` Functions

To get started with NumPy arrays, let's create an array having each item as `1` with dimensions `5` blocks, `3` rows and `3` columns.

To create such an array, you first need to `import` the `numpy` module at the beginning of the code. Then use the `ones()` function from the `numpy` module.

The `ones()` function requires two inputs. The first input should be the required dimension of the array and the second input should define the data-type of the items in the required array.

In [ ]:
# T1.1: Create an array containing '1' as its items using the 'ones()' function from the 'numpy' module.

# Step 1: Always import the 'numpy' module at the beginning of the code and give it an alias (or nickname) called np.
# We will always refer to the 'numpy' module as 'np' throughout the code.
import numpy as np

# Step 2: Call 'ones()' function from the np module using the dot operator.
# The 'ones()' function, requires two inputs: the dimension of the array and data-type of the items which in this case is 'int'.
ones = np.ones((5, 3, 3), dtype=int)
ones

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

**Note:**

1. Always import the `numpy` module at the beginning of the code with `np` as its alias (or nickname). Throughout the course, we will always refer to the `numpy` module as `np` unless otherwise specified.

2. The de facto data-type of an item in a NumPy array is `float`.

Using the `type()` function, you can verify whether an array is a NumPy array or not.

In [ ]:
# T1.2: Using the 'type()' function, verify whether the 'ones' array is a NumPy array or not.
type(ones)

numpy.ndarray

As you can see, the `type()` function has returned `numpy.ndarray` as an output which confirms that the `ones` array is indeed a NumPy array.

Similarly, you try to create a NumPy array having each item as `0` with dimensions `4` blocks, `2` rows and `3` columns using the `zeros()` function. Make sure that each item is an integer.

In [ ]:
# S1.1: Using 'zeros()' function, create a NumPy array having 4 blocks, 2 rows and 3 columns. The items should be int data-type.
zeros = np.zeros((4, 2, 3), dtype=int)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

Recreate the above array without providing the data-type as input. The output should be a three-dimensional array with each item as `0.` which is a floating-point number.

Here's the desired output:

```
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])
```

In [ ]:
# S1.2: Using 'zeros()' function, create a numpy array having 4 blocks, 2 rows and 3 columns.
zeros_float = np.zeros((4, 2, 3))
zeros_float

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

As you can see, all the items of the `zero_float` array are of `float` data-type.

---

#### Activity 2: The `dtype` Keyword

To check the data-type of the values stored in a NumPy array, you can use the `dtype` keyword.

In [ ]:
# S2.1: Using the 'dtype' keyword, verify whether the 'zeros_float' array items are floating-point values or not.
zeros_float.dtype

dtype('float64')

For the time being ignore the number `64`. As you can see, the `dtype` keyword has returned `dtype('float64')` as an output confirming that all the items of the `zeros_float` array are floating-point values.

In [ ]:
# S2.2: Using the 'dtype' keyword, verify whether the 'ones' array items are int values or not.
ones.dtype

dtype('int64')

For the time being ignore the number `64`. As you can see, the `dtype` keyword has returned `dtype('int64')` as an output confirming that all the items of the `ones` array are integer values.


**Difference Between The `type()` Function & The `dtype` Keyword**

The `type()` function is a function of Python. It returns the type of Python object. The data-types or more accurately the **primitive data-types** `int`, `float`, `str` and `bool` are actually Python objects. Similarly, Python lists, NumPy module, `random` modules are also Python objects. The `type()` function will tell you what type of Python objects they are.

In [ ]:
# S2.3: Run the code shown below to see that the 'type()' function returns the type of Python object.
import random
import numpy

# 1. The 'int' Python object.
print(type(2020))

# 2. The 'float' Python object.
print(type(3.14))

# 3. The 'str' Python object.
print(type('Earth'))

# 4. The 'list' Python object
print(type([i for i in range(1, 11)]))

# 5. 'numpy' is a 'module' Python object.
print(type(numpy))

# 6. 'random' is a 'module' Python object.
print(type(random))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'module'>
<class 'module'>

In the output, ignore the term `class`. As you can see, the `type()` function indeed returns the type of Python object for an entity in Python.

---

#### Activity 3: The `ndim` And `shape` Keywords

**The `ndim` Keyword:** Using the `ndim` keyword, you can find out the dimension of a NumPy array. The `ones`, `zeros` and `zeros_float` arrays are three-dimensional arrays. So, the `ndim` keyword should return `3` for each of these arrays.

In [ ]:
# Student Action: Using the 'ndim' array, find out the dimension of 'ones', 'zeros' and 'zeros_float' NumPy arrays.
print(ones.ndim)
print(zeros.ndim)
print(zeros_float.ndim)

3
3
3

**The `shape` Keyword:** Using the `shape` keyword, you can find out the number of blocks, rows and columns present in NumPy arrays.

In [ ]:
# Student Action: Using the 'shape' keyword find out the number of blocks, rows and columns in the 'ones', 'zeros' and 'zeros_float' arrays.
print(ones.shape)
print(zeros.shape)
print(zeros_float.shape)

(5, 3, 3)
(4, 2, 3)
(4, 2, 3)

As you can see:

- The `ones` array has 5 blocks, 3 rows and 3 columns.

- The `zeros` array has 4 blocks, 2 rows and 3 columns.

- The `zeros_ones` array also has 4 blocks, 2 rows and 3 columns.

---

#### Activity 4: The `arange()` And `linspace()` Functions^^

The are `arange()` and `linspace()` functions in NumPy module create an array of numbers such that the difference between a pair of any two consecutive numbers in the array is constant. However, there is a slight difference in their outputs.

**The `arange()` Function:** It returns a one-dimensional array containing numbers between two specific numbers. It is similar to the `range()` function in the `for` loop.

In [ ]:
# S4.1: Create a one-dimensional array containing numbers between 5 and 20 using the 'arange()' function in the NumPy module.
array1 = np.arange(5, 21)
array1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Here, the `arange()` function has created an array of numbers from `5` to `20`. The difference between a pair of any two consecutive numbers is `1`. The `arange()` function will not include the last number specified in the array created.

If you want the difference between two consecutive numbers to be greater than `1` (say `4`) in an array, then you can specify the difference as an additional input to the `arange()` function.

In [ ]:
# S4.2: Create an array of numbers from 1 to 24 such that the difference between two consecutive numbers is 4.
array2 = np.arange(1, 25, 4)
array2

array([ 1,  5,  9, 13, 17, 21])

As you can see, the `arange()` function has created an array of numbers from `1` to `24` such that the difference between two consecutive numbers is `4`.

**Note:** If the difference between two consecutive numbers is not specified, then the `arange()` function will assume that the difference is `1`.

You can also create an array containing the floating-point numbers using the `arange()` function by providing `dtype=float` as an additional input to the function.

In [ ]:
# S4.3: Create an array of numbers from 1 to 24 such that the difference between two consecutive numbers is 4 and each item is a float.
array3 = np.arange(1, 25, 4, dtype=float)
array3

array([ 1.,  5.,  9., 13., 17., 21.])

As you can see, the items contained in `array3` are floating-point numbers.

**The `linspace()` Function:** This function creates an array containing a fixed number of numbers between two specific numbers such that the difference between any two consecutive numbers in the array is constant. This will be clear to you with an example.

Suppose you want to create an array containing exactly `4` numbers between the numbers `1` and `25` such that all the difference between any two consecutive numbers is constant, then you can use the `linspace()` function.

In [ ]:
# S4.4: Create an array containing 4 numbers between 1 to 25.
array4 = np.linspace(1, 25, 4)
array4

array([ 1.,  9., 17., 25.])

As you can see, the `linspace()` function has created an array containing `4` numbers between `1` and `25` (including `25`) such that the difference between two consecutive numbers is constant. Take a pair of any two consecutive numbers in `array5`, the difference between them will be `8.`

Notice the difference between the outputs of the `arange()` and `linspace()` functions for exactly the same inputs. The `arange()` function returns `6` numbers such that the difference between them is exactly `4` whereas the `linspace()` function returns exactly `4` numbers such that the difference between two consecutive numbers is constant.

In other words:

- In the `arange()` function, you specify the value of the difference between two consecutive numbers as the third input.

- Whereas, in the `linspace()` function, you specify the length of the array to be created as the third input.

Let's create another array using the `linspace()` function to get a better understanding. Let's create an array containing `10` numbers between `1` and `25` such that the difference between two consecutive numbers is constant.

In [ ]:
# S4.5: Create an array containing 10 numbers between 1 and 25 such that the difference between two consecutive numbers is constant.
array5 = np.linspace(1, 25, 10)
array5

array([ 1.        ,  3.66666667,  6.33333333,  9.        , 11.66666667,
       14.33333333, 17.        , 19.66666667, 22.33333333, 25.        ])

Take a pair of any two consecutive numbers in the `array5`, the difference between them will be `2.66666666`

---

#### Activity 5: The `reshape()` Function


The `reshape()` function reshapes an array from one configuration to another without changing the items.

The `zeros` array has 4 blocks, 2 rows and 3 columns. Suppose you want to reshape it into another array having `6` rows and `4` columns without changing the items, then you can use the `reshape()` function.

In [ ]:
# Student Action: Reshape the 'zeros' array so that it has 6 rows and 4 columns.
# Before reshaping
print(zeros)

# After reshaping
reshaped_zeros = zeros.reshape(6, 4)
reshaped_zeros

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

The `reshape()` function has reshaped the `zeros` array to a two-dimensional array having 6 rows and 4 columns. Inside the `reshape()` function, you have to provide the new configuration.

This operation is only valid when the number of items in the new configuration is exactly the same as the number of items in the original configuration.

In this case, there are 24 items (4 blocks $\times$ 2 rows $\times$ $3$ columns = 24 items) in the original configuration. So the new configuration must also have 24 items.

You can also convert a multi-dimensional array into a one-dimensional array using the `reshape()` function. Let's convert `ones` into a one-dimensional array using the `reshape()` function. It has 45 items. The reshaped array must also contain 45 items.

In [ ]:
# Student Action: Reshape the 'ones' array so that it has just 1 row.
reshaped_ones = ones.reshape((45,)) # (45,) signifies that the array has just one row and 45 items.
reshaped_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

As you can see, the three-dimensional array is converted into a one-dimensional array using the `reshape()` function.

---

#### Activity 6: The `ndarray()` Function
In general, we can create a NumPy array containing some random values using `ndarray()` function.

Let's say we want to create a NumPy array having some random integer values which have 5 rows and 2 columns, then you can use the `ndarray()` function.

Similar to the `zeros()` and `ones()` functions, the `ndarray()` function takes two inputs: the first input is the configuration of the required array and the second input is the data-type of items. The de facto data-type is a floating-point value.

In [ ]:
# Student Action: Create a 'numpy' array using 'ndarray()' function having 5 rows and 2 columns.
some_array = np.ndarray((5, 2), dtype=int)
some_array

array([[4607182418800017408, 4615439018116863317],
       [4618816717837391189, 4621256167635550208],
       [4622757367511340373, 4624258567387130538],
       [4625478292286210048, 4626228892224105130],
       [4626979492162000213, 4627730092099895296]])

---

#### Activity 7: The `random.randint()` Function

The NumPy module also has its `random.randint()` function. It takes two inputs. The first input is the range of two integers between which a random number is to be created. The second input is the `size` parameter which defines the number of random integers to be created.

**Syntax:** `np.random.randint(num1, num2, size=N)`

 where `num1` and `num2` are starting numbers and `N` is the number of items to be contained in the array.

In [ ]:
# Student Action: Create a one-dimensional NumPy array containing 15 random integers between 50 and 100.
rand_1d_array = np.random.randint(50, 100, size=15)
rand_1d_array

array([69, 90, 55, 92, 96, 54, 60, 54, 72, 54, 87, 84, 55, 90, 90])

Similarly, you can create a multi-dimensional NumPy array containing random integers by specifying the dimensions of the array to be created in the `size` parameter.

In [ ]:
# Student Action: Create a two-dimensional NumPy array containing 15 random integers between 50 and 100.
rand_2d_array = np.random.randint(50, 100, size=(5, 3))
rand_2d_array

array([[81, 52, 63],
       [68, 77, 73],
       [56, 95, 57],
       [71, 58, 98],
       [65, 51, 71]])

In [ ]:
# Student Action: Create a three-dimensional NumPy array containing 40 random integers between 50 and 100.
rand_3d_array = np.random.randint(10, 50, size=(4, 2, 5))
rand_3d_array

array([[[44, 23, 48, 37, 30],
        [43, 37, 19, 35, 23]],

       [[21, 35, 36, 10, 31],
        [18, 22, 28, 49, 25]],

       [[26, 25, 13, 17, 39],
        [49, 28, 20, 26, 11]],

       [[45, 33, 33, 10, 13],
        [41, 42, 48, 26, 30]]])

---

#### Activity 8: The `array()` Function^

We can convert a Python list into a NumPy array. To do this, use the `array()` function which takes a Python list as an input.

Let's first create a list of natural numbers from `1` to `15` using the list comprehension method. Then convert the list into a NumPy array using the `array()` function.

In [ ]:
# Student Action: Convert a Python list into a NumPy array using the 'array()' function.
arr = np.array([i for i in range(1, 16)])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

To check whether a Python list is converted into a NumPy array or not, you can use the `type()` function.

In [ ]:
# Student Action: Verify whether the 'arr' array is a NumPy array or a Python list.
type(arr)

numpy.ndarray

---

#### Activity 9: The `list()` Function

We can convert a NumPy array into a Python list using the `list()` function.

Let's convert the `arr` NumPy array into a Python list using the `list()` function.

In [ ]:
# Student Action: Convert a NumPy array into a Python list using the 'list()' function.
arr_converted = list(arr)

Let's verify whether the conversion happened or not using the `type()` function.

In [ ]:
# Student Action: Verify whether the 'arr_converted' list is Python list or not.
type(arr_converted)

list

As you can see, the output is `list`. Hence, we successfully converted the NumPy array to a Python list using the `list()` function.

---

#### Activity 10: The `sqrt()` Function^^^

One of the most notorious concepts in maths is Heron's formula. It calculates the area of a triangle having sides $a, b \space \text{and} \space c$.

<img src='https://drive.google.com/uc?id=18SFm-ovV_QnKufMNNaXB6aWhIhT1cVki' width=500>

According to the Heron's formula, the area of a triangle is given by

$$\text{Area} = \sqrt{s(s-a)(s-b)(s-c)}$$

where

$$s = \frac{a + b + c}{2}$$

i.e., the semi-perimeter of a triangle.

Let's create a function which takes the lengths of the sides of a triangle and checks whether the lengths indeed represent the lengths of the sides of a triangle.

*The sum of lengths of any two sides of a triangle is always greater than the length of the third side.*

If the lengths meet the criteria for being the lengths of the sides of a triangle, then the function should return `True`. Else it should return `False`.

In [ ]:
# Student Action: Create a function to check whether the input lenghts represent the lengths of the side of a triangle.
def is_triangle(a, b, c):
  if ((a + b) > c) and ((a + c) > b) and ((b + c) > a):
    return True
  else:
    return False

is_triangle(5, 6, 7)

True

Now, let's create a function to calculate the area of a triangle using the Heron's formula. The function must include the `is_triangle()` function and `np.sqrt()` functions. If the invalid side lengths are passed as input to the function, then it should return `Invalid triangle.` message else it should return the area of a triangle.

In [ ]:
# Student Action: Create a function to calculate the area of a triangle using the Heron's formula.
def heron_formula(a, b, c):
  if is_triangle(a, b, c) == True:
    s = (a + b + c) / 2
    return np.sqrt(s * (s - a) * (s - b) * (s - c))
  else:
    return "Invalid triangle."

print(heron_formula(5, 1, 7))
heron_formula(5, 6, 7)

Invalid triangle.

14.696938456699069

Alternatively, you can raise a number to the power `0.5` to calculate the square root of a number, but it will return a complex number as an output for a negative number. On the other hand, the `np.sqrt()` function returns `nan` for negative numbers. It stands for **not a number** and denotes a NumPy null value.

---

### Additional Activities

The activities starting from this point are optional. Please do these activities **ONLY** if you have time to spare in the class. Otherwise, skip to the **Wrap-Up** section. The additional activities will not be available in the class copy of the notebook. You will have to manually add these activities in the class copy by adding new text and code cells.

Moreover, you don't have to do all the additional activities. Depending on the availability of time in a class, you can choose the number of additional activities to perform from this collection.

---

#### Activity 1: Trigonometric, Exponential & Logarithmic Functions

In [ ]:
# Create a list of angles representing angles either angles in radians or degrees.
angles = np.arange(0, 95, 15)
angles

array([ 0, 15, 30, 45, 60, 75, 90])

**The `np.sin()` Function**

In [ ]:
# Calculate the sine of the angles.
np.sin(np.deg2rad(angles))

array([0.        , 0.25881905, 0.5       , 0.70710678, 0.8660254 ,
       0.96592583, 1.        ])

**The `np.cos()` Function**

In [ ]:
# Calculate the cosine of the angles.
np.cos(np.deg2rad(angles))

array([1.00000000e+00, 9.65925826e-01, 8.66025404e-01, 7.07106781e-01,
       5.00000000e-01, 2.58819045e-01, 6.12323400e-17])

**The `np.tan()` Function**

In [ ]:
# Calculate the tangent of the angles.
np.tan(np.deg2rad(angles))

array([0.00000000e+00, 2.67949192e-01, 5.77350269e-01, 1.00000000e+00,
       1.73205081e+00, 3.73205081e+00, 1.63312394e+16])

**The `np.exp()` Function**

In [ ]:
# Calculate the first 10 powers of the Napier's constant (or e).
exp = [np.exp(i) for i in range(1, 11)]
exp

[2.718281828459045,
 7.38905609893065,
 20.085536923187668,
 54.598150033144236,
 148.4131591025766,
 403.4287934927351,
 1096.6331584284585,
 2980.9579870417283,
 8103.083927575384,
 22026.465794806718]

**The `np.log()` Function**

The default base of `np.log()` function is $e = 2.7182$ or `np.exp(1)`

In [ ]:
np.log(exp)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

To get the logarithms of a number $a$, i.e., $\text{log}_{10} a$, use the `np.log10()` function.

In [ ]:
np.log10([10 ** i for i in range(1, 11)])

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

---

#### Activity 2: Union & Intersection

To get the common items between two distinct one-dimensional arrays, use the `np.intersection1d()` function.

To get all the items of two distinct one-dimensional arrays, use the `np.union1d()` function.

In [ ]:
# Create two distinct one-dimensional arrays and get the items common between them.
array1 = np.arange(1, 11)
array2 = np.arange(6, 26)
np.intersect1d(array1, array2)

array([ 6,  7,  8,  9, 10])

In [ ]:
# Get all the items of two distinct one-dimensional arrays created above.
np.union1d(array1, array2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

---

### Wrap-Up

```
TEACHER
  Did you enjoy the class?

EXPECTED STUDENT RESPONSE
  Yes, teacher.


TEACHER
  What part of the class did you enjoy?

EXPECTED STUDENT RESPONSE
  I enjoyed everything.


TEACHER
  I am glad you are having a good time. But make sure that you practice
  writing code in your free time.

EXPECTED STUDENT RESPONSE
  Sure teacher.


TEACHER
  In the next class, we will perform some of the mathematical
  operations using NumPy arrays and we will also compare the performance of
  a NumPy array with a Python list.

EXPECTED STUDENT RESPONSE
  Sure teacher.


TEACHER
  See you in the next class. Bye!

EXPECTED STUDENT RESPONSE
  Bye teacher!
```

---

### Activities

**Teacher Activities**

1. NumPy Arrays I (Class Copy)

   Link on Panel

2. NumPy Arrays I (Reference)

   Link on Panel

---