# Lesson 13: Pandas Series

**WARNING:** The reference notebook is meant **ONLY** for a teacher. Please **DON'T** share it with any student.

The contents of the reference notebook are meant only to prepare a teacher for a class. To conduct the class, use the class copy of the reference notebook. The link and the instructions for the same are provided in the **Notes To The Teacher** section.


|Particulars|Description|
|-|-|
|**Topic**|Pandas Series|
|||
|**Class Description**|In this class, a student will create a Pandas series|
|||
|**Class**|C13|
|||
|**Class Time**|45 minutes|
|||
|**Goal**|Create a Pandas series|
||Retrieve an item from a Pandas series|
||Apply basic statistical operations on a Pandas series|
|||
|**Teacher Resources**|Google Account|
||Link to Lesson 13 Colab reference notebook|
||Laptop with internet connectivity|
||Earphones with mic|
|||
|**Student Resources**|Google Account|
||Laptop with internet connectivity|
||Earphones with mic|

---

### Class Structure

A class is divided into three parts, as shown in the table below.

|Parts|Duration|
|-|-|
|**Warm-Up**|5 minutes|
|||
|**Teacher-Student Activities**|35 minutes|
|||
|**Wrap-Up**|5 minutes|

---

### Notes To The Teacher

Before beginning the class:

1. Open the **AT - Lesson 13 - Class Copy - v0.1** file by clicking on the link provided in the **Activities** section under the title **Pandas Series (Class Copy)**.  

2. After opening the file mentioned in the first point, create its duplicate copy by following the steps described below:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

    - In the duplicate copy, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/2_share_button.png' width=500>

    - Click on the tiny downward arrow next to **Anyone with the link can view** text. A drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/3_anyone_can_view.png' width=500>

    - Click on the **More...** option. A new page on the dialog box will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/4_more_option.png' width=500>

    - Click on the circle next to **On - Anyone with the link** option. Now, go down and click on the tiny downward box next to **Can edit** text. A drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/5_anyone_with_the_link.png' width=500>

    - Click on the **Can edit** option. Then click on the **Save** button. You will be directed back to the first page of the dialog box.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/6_can_edit.png' width=500>

    - Make sure that under the **Link sharing on** section, **Anyone with the link can edit** option is selected.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/7_anyone_can_edit.png' width=500>

    - Then click on the **Done** button.

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Lesson13** format.

4. Now, finish the **Warm-Up** section. Afterwards, proceed with the class using the duplicate copy of the notebook. You can share the link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Lesson13**) with the student through the chat window.

5. When a student executes the code for the first time in the duplicate copy that you shared with them, they may get the following warning:

   ```
    Warning: This notebook was not authored by Google. This notebook was
    authored by xyz@gmail.com. It may request access to your data stored
    with Google such as files, emails and contacts. Please review the source
    code and contact the creator of this notebook at xyz@gmail.com with any
    additional questions.

                                                      Cancel. Run Anyway.
  ```

6. Ask the student to click on the `Run Anyway` button.

7. Wherever you see the hat (**^**) sign on the heading of activity, give a hats-off to the student at the end of the activity.

    - Single hat sign, i.e., **^** denotes give hats-off for concentration. You have to assess the concentration level of a student based on their attentiveness and understanding of the concept.

    - Double hat signs, i.e., **^^** denotes give hats-off for creativity. It can be an alternative approach to writing a code for an activity or applying the logic in a totally different problem statement.

    - Triple hat signs, i.e., **^^^** denotes give hats-off for persistence. It is the ability of a student to not give up on writing code and writing code with minimal teacher support.

8. Every time you execute your code in the Google Colab notebook, please don't forget to save it by pressing the **Ctrl + S** keys (or **Command + S** keys if you are using a Mac). While saving the notebook, you or student may encounter the following error:

   ```
    Save failed
    
    The notebook has been changed outside of this session. Would you like to
    overwrite existing changes?
    
                                                              CANCEL    YES
   ```

   Click on the `YES` button.

9. Occasionally, you may encounter some error such as `NameError, ReferenceError, ImportError` or `ModuleNotFoundError` after executing the code in $k^{th}$ code cell (where $k > 0$). Most likely, due to poor internet speed, the Colab notebook might have lost the information that all the previous codes have been executed already. As a remedy, run codes in the code cells beginning from the first code cell till the $(k - 1)^{th}$ code cell. For e.g., if the code in the $5^{th}$ code cell fails to run because of one of the aforementioned errors, execute the codes in all the first four code cells again.

10. For every **Teacher Action**, the teacher is supposed to share their screen with the student. Similarly, for every **Student Action**, the student is supposed to share their screen with the teacher.

---

### Warm-Up

```
TEACHER
  Hi student_name! How are you doing?

EXPECTED STUDENT RESPONSE
  I am doing good, teacher. How about you?


TEACHER
  I am having a good time, thank you. So, how was your day? What did you do
  today?

EXPECTED STUDENT RESPONSE
  I went to school. Had my lunch. Played a game and then did my homework
  before this class.


TEACHER
  That's great. I am glad that you are having a good day. Now, let's do a
  quick recap of our previous class. Can you recall the concepts you
  learnt in the previous lesson?

EXPECTED STUDENT RESPONSE
  We learnt how to create the Mind Reader game algorithm which makes
  accurate predictions. The algorithm is based on Claude Shannon's
  "A Mind Reading Machine".


TEACHER
  Excellent! You recalled everything that you learnt in the last class.
  Great job! Keep it up.
  I have an exciting quiz question for you! Are you ready to answer this question?    
  ```   
  **Instructions for the Teacher:**
  -  Please click on the "Quiz Time" button on the bottom right corner of your screen to start the In-Class Quiz.<img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/quiz-time.png' width=100>   
  - A quiz will be visible to both you and the student. Encourage the student to answer the quiz question.
  - The student may choose the wrong option, help the student to think correctly about the question and then answer again.
  - After the student selects the correct option, the "End Quiz" button will start appearing on your screen.  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/end-quiz.png' width=100>  
  - Click the "End quiz" to close the quiz pop-up and continue the class.
  - Do not spend more than 2 minutes on this quiz.

```
TEACHER
  Today, we are going to learn Pandas series. Similar to Python lists and NumPy
  arrays, a Pandas series can store data. This is an introductory class to
  Pandas to familiarise you with a few basic Pandas functions that are very
  frequently used in data interpretation.
  
  So, are you excited for this class?

EXPECTED STUDENT RESPONSE
  Yes, teacher.


TEACHER
  All right. Let's get started. I'm sharing the link to the Colab notebook
  for this class. Open it up.

  Note:
    - Share the duplicate copy of the Colab notebook that you just created
      with the student through the chat window.
    
EXPECTED STUDENT RESPONSE
  The student opens the Colab notebook shared by the teacher.
```

---

### Teacher-Student Activities

Before we go ahead with more concepts on Machine Learning and Artificial Intelligence, let's first learn a bit of Data Analysis, so that you can get a better understanding of data. Every dataset tells you a story if you look at it through the right lenses.

To give you a perspective, imagine that you have data on the number of sales happening in every month of every single shop in your city. You would notice that during the festivals, the sales volume of sweets rises by a tremendous magnitude. Similarly, the sales volume of clothes, jewellery and electronic products also rose significantly in this period.

If you have the tourism data, then you would see that a lot of people in India go on a vacation in the months of May and June, which makes sense because schools are closed in these two months due to summer vacation.

Through data, you can observe a trend and based on that trend you can draw meaningful insights, helping you in making decisions in your daily life, in business organisations, in medical and engineering applications etc.

When it comes to Data Analysis in Python, we use a module called Pandas which is specifically designed to manipulate, manage and analyse a huge amount of data by creating Pandas Series and Pandas DataFrames.

In this lesson, we will learn about the Pandas Series.

---

#### Pandas Series

A Pandas series is a one-dimensional array which can hold various data types. It is similar to a Python list and a NumPy array.

Without going too much into the theory, let's get started with the Pandas series right away. At the end of the class, we will learn when to use a Python list, a NumPy array and a Pandas series.

---

#### Activity 1: Python List To Pandas Series Conversion

Let's understand the Pandas series through an example. Suppose there are `30` students in your class and their weights vary in the range of `45` to `60` kg (both inclusive).

We can create a Pandas series containing the weights of the students by first creating a Python list and then converting it to a Pandas series. To create a Pandas series, you have to first import the `pandas` module using the `import` keyword.

```
import pandas as pd
```

Here, `pd` is an alias (or nickname) for `pandas`

Then you can call the `Series()` function to convert a Python list or a NumPy array into a Pandas series.

```
weights = pd.Series([random.randint(45, 60) for i in range(30)])
```

**Note:** Unlike other functions, the `Series()` function begins with the uppercase letter `S`.

In [ ]:
# Teacher Action: Create a Pandas series containing 30 random integers between 45 and 60.
import random
import pandas as pd

weights = pd.Series([random.randint(45, 60) for i in range(30)])
weights

0     55
1     57
2     54
3     60
4     58
5     52
6     47
7     60
8     59
9     56
10    60
11    53
12    55
13    58
14    50
15    52
16    48
17    46
18    58
19    59
20    58
21    57
22    56
23    52
24    47
25    49
26    55
27    49
28    59
29    58
dtype: int64

The first column in the output represents the indices of all the items in the `weights` Pandas series. The second column contains the weights of the students. The data-type of each item is an `int`.

**Note:** Ignore the `64` in the `int64` for the time being.

Using the `Series()` function, you can convert any one-dimensional Python list into a Pandas series. Now, let's verify whether `weights` is a Pandas series or not.

In [ ]:
# Student Action: Verify the type of value stored in the 'weights' variable using the 'type()' function.
type(weights)

pandas.core.series.Series

The `type()` function returns `pandas.core.series.Series` as an output which confirms that `weights` is indeed a Pandas series.

A Pandas series can also contain the items of multiple data-types. Recall that in the trial class we created 4 different variables to store the attributes of a planet.  

||Mercury|
|-|-|
|Diameter (km)|4879|
|Gravity ($m/s^2$)|3.7|
|Ring|No|


Let's store the name of a planet, its diameter, gravity and whether it has a ring or not in a Python list and then convert it into a pandas series.

In [ ]:
# Student Action: Create a Python list which contains planet name, diameter, gravity and False if the planet has a ring.
# Convert the list into a Pandas series. Also, verify whether the list successfully is converted to a Pandas series or not.
planet_details = pd.Series(['Mercury', 4879, 3.7, False])
print(planet_details)
type(planet_details)

0    Mercury
1       4879
2        3.7
3      False
dtype: object

pandas.core.series.Series

Here the data-type is `object`. Pandas cannot return the data-type of every individual item. Hence, it has returned `object` data-type to represent one common data-type for all the items.

You can also use the `size` keyword to find the number of items in a Pandas series.

In [ ]:
# Student Action: Find the number of items in the 'weights' Pandas series using the 'size' keyword.
weights.size

30

So, there are `30` items in the `weights` Pandas series.

You can also use the `shape` keyword to find the number of rows and columns in a Pandas series.

In [ ]:
# Student Action: Find the number of rows and columns in the 'weights' Pandas series using the 'shape' keyword.
weights.shape

(30,)

So, there are `30` rows and `1` column in the `weights` Pandas series.

---

#### Activity 2: The `mean(), min(), max()` Functions

The `mean()` function does not take any input and returns the average value of all the items as an output.

To apply this function, you need to write the Pandas series; whose mean value you need to compute; followed by the dot (`.`) operator.

In [ ]:
# Student Action: Calculate the average value of all the numbers in a Pandas series.
weights.mean()

54.56666666666667

Similarly, you can also find the minimum and maximum values in a Pandas series using the `min()` and `max()` functions.

In [ ]:
# Student Action: Using the 'min()' and 'max()' functions, print the minimum and maximum values in the 'weights' Pandas series.
print(weights.min())
weights.max()

46

60

---

#### Activity 3: The `head()` And `tail()` Functions

Sometimes instead of looking at the full dataset, we just want to look at the first few rows or the last few rows of the dataset. In such cases, we can use the `head()` and `tail()` function.

The `head()` function shows the first five and the `tail()` function shows the last five items in a Pandas series.

In [ ]:
# Student Action: Print only the first 5 items in a Pandas series using the 'head()' function.
weights.head()

0    55
1    57
2    54
3    60
4    58
dtype: int64

The numbers in the first column in the output are the indices of each item in the Pandas series. Since we print the first five items, the indices range from `0` to `4`.

In [ ]:
# Student Action: Using the 'tail()' function, print the last 5 items in the Pandas series.
weights.tail()

25    49
26    55
27    49
28    59
29    58
dtype: int64

Since we printed the last five items of the series, the indices range from `25` to `29`.

Within the `head()` and `tail()` functions, you can specify the `n` number of first items and the `n` number of last items you wish to see in a Pandas series.

In [ ]:
# Student Action: Using the 'head()' function, print the first 8 items of the weights series.
weights.head(8)

0    55
1    57
2    54
3    60
4    58
5    52
6    47
7    60
dtype: int64

In [ ]:
# Student Action: Using the 'tail()' function, print the last 12 items of the weights series.
weights.tail(12)

18    58
19    59
20    58
21    57
22    56
23    52
24    47
25    49
26    55
27    49
28    59
29    58
dtype: int64

---

#### Activity 4: Indexing A Pandas Series^

Indexing a Pandas series is the same as indexing a Python list or a NumPy array.

Let's say we want to get the weights of the students whose indices range from `13` to `21`, then you can write the variable storing the Pandas series followed by the square brackets `[]`. Inside the square brackets, you can mention the range of items you wish to retrieve from a series.

**Syntax:** `pandas_series[start_index:end_index]`

In [ ]:
# S4.1: Retrieve items from a Pandas series using the indexing method.
weights[13:22]

13    58
14    50
15    52
16    48
17    46
18    58
19    59
20    58
21    57
dtype: int64

In [ ]:
# S4.2: Print the items ranging from the indices 17 to 27.
weights[17:28]

17    46
18    58
19    59
20    58
21    57
22    56
23    52
24    47
25    49
26    55
27    49
dtype: int64

---

#### Activity 5: The `mode()` Function

Let's say you want to find out the weights of the most number of students in your class, then you can use the `mode()` function.

In [ ]:
# Student Action: Compute the modal value in the 'weight' series.
weights.mode()

0    58
dtype: int64

**Note**: A dataset can have more than one modal value.

---

#### Activity 6: The `sort_values()` Function^^

We can use the `sort_values()` function to arrange the numbers in a Pandas series either in an ascending order or in descending order.

To arrange the numbers in a Pandas series in the increasing order, use the `sort_values()` function with the `ascending=True` as an input.

In [ ]:
# Student Action: Arrange the weights in the increasing order using the 'sort_values()' function.
weights.sort_values(ascending=True)

17    46
6     47
24    47
16    48
27    49
25    49
14    50
5     52
23    52
15    52
11    53
2     54
26    55
0     55
12    55
9     56
22    56
21    57
1     57
18    58
20    58
4     58
13    58
29    58
28    59
19    59
8     59
10    60
7     60
3     60
dtype: int64

To arrange the numbers in a Pandas series in the decreasing order, use the `sort_values()` function with the `ascending=False` as an input.

In [ ]:
# Student Action: Using the 'sort_values()' function, arrange the weights in the decreasing order.
weights.sort_values(ascending=False)

3     60
7     60
10    60
8     59
19    59
28    59
29    58
13    58
4     58
20    58
18    58
1     57
21    57
22    56
9     56
12    55
0     55
26    55
2     54
11    53
15    52
23    52
5     52
14    50
25    49
27    49
16    48
24    47
6     47
17    46
dtype: int64

---

#### Activity 7: The `median()` Function

To find the median value in a Pandas series, we can simply use the `median()` function.

In [ ]:
# Student Action: Using the 'median()' function, find the median weight in the weights series.
weights.median()

55.5

---

#### Activity 8: The `value_counts()` Function^^^

To count the number of occurrences of an item in a Pandas series, you can use the `value_counts()` function.

In [ ]:
# Student Action: Count the number of times each item in the 'weights' Pandas series occurs.
weights.value_counts()

58    5
60    3
59    3
55    3
52    3
57    2
56    2
49    2
47    2
54    1
53    1
50    1
48    1
46    1
dtype: int64

**Note:** The `value_counts()` function is not available for Python lists and NumPy arrays.

There is more to the Pandas series. We will learn it in detail along with Pandas DataFrames from the next class onwards. This is just an introductory class to Pandas.

---

#### Python List vs NumPy Array vs Pandas Series

You might now wonder when to use a Python list, a NumPy array and a Pandas series?

There are no hard rules to decide when to use which one of these data-structures but as a guide you may consider the following:

1. When you just want to store data, retrieve data and add more data, use a Python list.

2. When you want to store a numerical data (one-dimensional or multidimensional) and want to perform a lot of mathematical operations, then use a NumPy array as it faster than a Python list and it is easy to create a multidimensional array using a NumPy array.

3. When you want to import data from an external file such as `TXT, XLXS, CSV, XML` etc then use a Pandas series. In the next class, you will learn how to import data from an external file. Additionally, Pandas allow you to interpret data in different ways. It also allows you to do complicated data extraction, manipulation and data processing operations on a dataset. Throughout this course, we will use Pandas library to handle data.

---

### Additional Activities

The activities starting from this point are optional. Please do these activities **ONLY** if you have time to spare in the class. Otherwise, skip to the **Wrap-Up** section. The additional activities will not be available in the class copy of the notebook. You will have to manually add these activities in the class copy by adding new text and code cells.

Moreover, you don't have to do all the additional activities. Depending on the availability of time in a class, you can choose the number of additional activities to perform from this collection.

---

#### Activity 1: Calculate Mean

Write a function to calculate the mean of all the numbers contained in a list/array/series.

In [ ]:
# Solution
def compute_mean(num_series):
  result = 0
  for num in num_series:
    result = result + num
  return result / len(num_series)

num_series = pd.Series([i for i in range(1, 11)])
print(num_series)
print("The required mean is", compute_mean(num_series))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
The required mean is 5.5

---

#### Activity 2: Calculate Median

Write a function to calculate the median of all the numbers contained in a list/array/series.

In [ ]:
# Solution
def compute_median(num_series):
  result = 0
  num_list = [num for num in num_series]
  num_list.sort()
  if len(num_list) % 2 == 0:
    result = (num_list[(len(num_list) // 2) - 1] + num_list[len(num_list) // 2]) / 2
  else:
    result = float(num_list[len(num_list) // 2])
  return result

num_series = pd.Series([random.randint(30, 60) for i in range(10)])
print("Median without using the standard median() function:", compute_median(num_series))
print("Median using the standard median() function:", num_series.median())

Median without using the standard median() function: 39.5
Median using the standard median() function: 39.5

---

#### Activity 3: The `head()` & `tail()` Functions With Negative Inputs

Let `pd_series` be a Pandas series which contains `N` number of elements. Let `n` be some positive integer such that `n < N`.

The `pd_series.head(-n)` operation will return the **first** `N - n` items contained in the `pd_series`.

In [ ]:
# 'head()' with negative input.
weights.head(-8)

0     55
1     57
2     54
3     60
4     58
5     52
6     47
7     60
8     59
9     56
10    60
11    53
12    55
13    58
14    50
15    52
16    48
17    46
18    58
19    59
20    58
21    57
dtype: int64

The `pd_series.tail(-n)` operation will return the **last** `N - n` items contained in the `pd_series`.

In [ ]:
# 'tail()' with negative input.
weights.tail(-8)

8     59
9     56
10    60
11    53
12    55
13    58
14    50
15    52
16    48
17    46
18    58
19    59
20    58
21    57
22    56
23    52
24    47
25    49
26    55
27    49
28    59
29    58
dtype: int64

---

### Wrap-Up

```
TEACHER
  Did you enjoy the class?

EXPECTED STUDENT RESPONSE
  Yes teacher.


TEACHER
  What part of the class did you enjoy?

EXPECTED STUDENT RESPONSE
  I enjoyed everything.


TEACHER
  I am glad you are having a good time. But make sure that you practice
  writing code in your free time.

EXPECTED STUDENT RESPONSE
  Sure teacher.


TEACHER
  In the next class, we will learn Pandas DataFrames. Going forward we will
  use Pandas DataFrames very frequently to analyse, manipulate and manage
  data.

EXPECTED STUDENT RESPONSE
  Sure teacher.


TEACHER
  See you in the next class. Bye!

EXPECTED STUDENT RESPONSE
  Bye teacher!
```

---

### Activities

**Teacher Activities**

1. Pandas Series (Class Copy)

   Link on Panel
   
2. Pandas Series (Reference)

   Link on Panel

---